match fuzzy logic to updates from #48
castelao/CoTeDe pull request #53
Opened 2020-12-25 00:56 UTC by BillMills

Hi @castelao - here's my best guess for how to resolve the problem I was mentioning in https://github.com/IQuOD/AutoQC/pull/261#issuecomment-744108074.

It seems that back in #48, you dropped the masks for things like spike and gradient results, and replaced masked values with NaNs. Problem is that fuzzy_core was using those masks to decide which levels in a profile to look at; this change tells fuzzy_core to look for NaNs instead of masks.

As always, you know best whether this actually makes sense, and if there are any other places in the code that might need a similar change. Running AutoQC over 1000 profiles with this change hacked into CoTeDe produces qualitatively reasonable looking results - instead of flagging all 1000 profiles as discussed in https://github.com/IQuOD/AutoQC/pull/261, I get:

```
                       NAME OF TEST   FAILS     TPR     FPR     TNR     FNR
                 CoTeDe_Morello2014     395   65.5%   20.9%   79.1%   34.5%
                 CoTeDe_fuzzy_logic     267   54.0%    7.2%   92.8%   46.0%
```

Which is in line (though again improved) compared to what we were seeing in earlier releases of CoTeDe.

2020-12-28 21:46 UTC, castelao requested changes
@BillMills, thanks !

For now it is safer to do `ind = (~ma.getmaskarray(features[t]) & np.isfinite(features[t]))`.

Don't worry about creating tests. I'm refactoring the fuzzy procedure and I'll take care of the validation tests. Please, remember to update the AUTHORS.rst. Maybe another bullet there?

2020-12-30 14:47 UTC, BillMills commented
Thanks @castelao - your suggestions implemented verbatim. Results still look good in AutoQC with these changes, too.

2021-01-03 03:08 UTC, castelao approved these changes

2021-01-03 03:10 UTC, castelao commented
@BillMills , thank you so much!

2021-01-03 03:11 UTC, merged